# Site settings
title: "和歌山のITコミュニティ Wacker"
header-img: img/wacker.png
copyright_name: "Wacker"
description: "和歌山のITエンジニアによるコミュニティ"
baseurl: ""
url: "http://wacker.io"
github_username: wakayama-hacker
facebook_username: groups/1329180433777951/

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
exclude: [vendor]
